menus:
  -
    menu_name: main
    title: Media
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '1'
    weight: '12'
    langcode: fr
    uuid: a1fb0259-be99-4312-8c6f-348aa4ec261e
    options: null
taxonomies:
  icons:
    -
      vid: icons
      tid: '1'
      langcode: fr
      name: 'Accès handicapé'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 25bd3efa-b357-4881-baba-465f3f53e6e8
    -
      vid: icons
      tid: '2'
      langcode: fr
      name: 'Balise radio'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3f8807b8-c0f1-48bb-a7ec-860224195aa6
    -
      vid: icons
      tid: '3'
      langcode: fr
      name: Bar
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: e04f972d-5433-41e9-8a1b-d937554a6c22
    -
      vid: icons
      tid: '4'
      langcode: fr
      name: Bivouac
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1a442c3c-e1eb-479f-af1d-02944fc0f71a
    -
      vid: icons
      tid: '5'
      langcode: fr
      name: CB
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: a6d2d3c3-1990-4f73-b888-c1b92a95a635
    -
      vid: icons
      tid: '6'
      langcode: fr
      name: Chauffage
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 9b9a89cf-4f81-49a4-a77b-19f9be5bb9d4
    -
      vid: icons
      tid: '7'
      langcode: fr
      name: Couverture
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 452ce150-b353-4f6f-82b1-ca6fcfa2dac1
    -
      vid: icons
      tid: '8'
      langcode: fr
      name: Defebrilateur
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 4e8362ca-1207-42b3-8d40-d59d14a4533f
    -
      vid: icons
      tid: '9'
      langcode: fr
      name: Dortoirs
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1bc4910b-c6c0-426d-b217-ceac11e00b2a
    -
      vid: icons
      tid: '10'
      langcode: fr
      name: Douche
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 18ca5af8-53b3-494e-ac77-e29578826f1c
    -
      vid: icons
      tid: '11'
      langcode: fr
      name: 'Eau potable'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7857ddec-5f0e-4a9e-b2db-d22482b068b8
    -
      vid: icons
      tid: '12'
      langcode: fr
      name: Lumière
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1409f72d-e6f5-4534-9ef4-4c1c257ef340
    -
      vid: icons
      tid: '13'
      langcode: fr
      name: 'Nombre de couchaches'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ad469c9f-7113-40c3-b5b5-357aab69707f
    -
      vid: icons
      tid: '14'
      langcode: fr
      name: Pharmacie
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7e848f02-6f43-433f-8e72-e0c536c529b1
    -
      vid: icons
      tid: '15'
      langcode: fr
      name: 'Plaque de cuisson'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3043d59d-780c-4842-a95f-c5bee62bc01c
    -
      vid: icons
      tid: '16'
      langcode: fr
      name: 'Prise électrique'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: a1f32a53-8a21-4e9f-9c2b-f35369613b94
    -
      vid: icons
      tid: '17'
      langcode: fr
      name: Restauration
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 5a044e6b-de2d-4c23-bdfd-46b46950e45d
    -
      vid: icons
      tid: '18'
      langcode: fr
      name: 'Salle hors sac'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 39f16277-8a6a-4061-8293-52de1349511d
    -
      vid: icons
      tid: '19'
      langcode: fr
      name: Toilettes
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 941d681f-7005-4bfb-bcc0-508ea2ff7d5e
    -
      vid: icons
      tid: '20'
      langcode: fr
      name: Vaisselle
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 06bef5d7-dc8f-4fb3-98e3-913249685ab1
    -
      vid: icons
      tid: '21'
      langcode: fr
      name: Wifi
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 30ea2e0f-cc06-4274-8d2c-f16d437770e2
blocks:
  -
    info: 'Coordonnées du refuge'
    langcode: und
    uuid: 6a48bd26-d78d-4f62-92c0-b0cfc8b9e2c0
    bundle: contact_details
    revision_id: null
    rev_id_current: null
    fields:
      field_email:
        value: refuge.arpont@vanoise-parcnational.fr
      field_phone:
        value: '09 82 12 42 13'
      field_postal_address:
        value: "TERMIGNON\r\n73500 VAL-CENIS"
  -
    info: Partenaires
    langcode: und
    uuid: 9b2300b4-38a4-407d-bf8f-14cc8c61fbc5
    bundle: bloc_partenaires
    revision_id: null
    rev_id_current: null
    fields:
      field_partner_logo:
        target_id: '46'
        alt: 'Esprit Parc National'
        title: ''
        width: '280'
        height: '202'
        link_uri: 'http://www.espritparcnational.com/parcs-nationaux/parc-national-de-la-vanoise'
        link_title: null
        link_options: {  }
        link_display_settings:
          formatter_settings: false
          image_link: ''
          link_title_display: false
          link_title_tag: ''
          link_title_position: ''
          link_rel: false
          link_target: false
  -
    info: 'Bloc d''intro de la page Services'
    langcode: fr
    uuid: 6d6f6b90-7ad4-4506-91dd-efb85fe52a20
    bundle: intro_block
    revision_id: null
    rev_id_current: null
    fields:
      field_intro_block_footer:
        value: "<p>En période :</p>\r\n"
        format: full_html
      field_intro_block_header: null
      field_intro_block_text:
        value: "<p>Lorem ipsum dolor sit amet,sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, &nbsp;At vero eos et accusam et justo duo dolores et ea rebum. &nbsp;Lorem ipsum dolor sit amet, &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;Stet clita kasd gubergren, &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;sed diam voluptua. &nbsp;</p>\r\n"
        format: full_html
      field_intro_block_title:
        value: 'Sous-titre de la page Services'
